#!/usr/bin/perl

use strict;
use warnings;
#Use functions from perl 5.012
use 5.012;
use HelloWorld;

my $arg=undef;

#Check list if empty
if(@ARGV) {
    $arg=$ARGV[0];
} else {
    $arg=<>;
}

my $var = HelloWorld::argumentTest($arg);
#Same as print but with newline
say "$var";